### PR TITLE
Check auth status before bind on firebase db change

### PR DESCRIPTION
**Pull request by kidphys**

### CODE REVIEW

**Comment by kidphys** [comment]
@sidferreira Could you help review the pull request?

**Comment by shrmnk** [comment]
I saw that you added support for sorting. Did you include `array-sort` in the dependencies?

**Comment by grahamlyus** [comment]
@kidphys Seems to me like the filtering and sorting should be separate PRs - I don't use the auth client so can't verify that fix

**Comment by sidferreira** [comment]
@grahamlyus I'll take a look on the auth thing this week. Might also work on the upload too

**Comment by sidferreira** [comment]
@kidphys @shrmnk Guys, can you help splitting this PR?

**Comment by shrmnk** [comment]
@sidferreira Alright I've created a PR just for the sorting. @kidphys hope you don't mind! I had this functionality on my production site so was ready to put it up.

**Comment by grahamlyus** [comment]
Good point - I haven't used any public resources in my little project, but I could see that being an issue.

**Comment by grahamlyus** [comment]
@sidferreira @shrmnk @kidphys 

Upon further reflection, it seems unlikely that an unauthenticated user would have access to the admin, regardless of the actual database permissions, so maybe it's a moot point?

**Comment by shrmnk** [comment]
Agreed on that. I think it’s unlikely a site will have a mix of public/unauthenticated admin pages with protected ones.

**Comment by sidferreira** [comment]
@grahamlyus @shrmnk true... but it will force the user always setup the auth part. Start and admin without auth to add it later will not be possible, as it will wait for the usetAuth callback.

**Comment by sidferreira** [comment]
@kidphys @grahamlyus @shrmnk I'm about to release v0.2.0 which has it fixed. I'm finishing the tests. Feel free to use/test and help me out!

**Pull request closed without merging**
